import type { Metadata } from "next";
import "../styles/globals.scss";
import Providers from "../layout/providers";
import Head from "next/head";

export const metadata: Metadata = {
  title: 'Demo App',
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // for basic browsers
    shortcut: "/favicon.ico", // for Safari
    apple: "/apple-touch-icon.png", // for Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Head>
          <link id="theme-link" rel="stylesheet" href="/theme/lara-dark-green/theme.css"></link>
          <link id="theme-ref" rel="stylesheet" href="/themes/primeone-dark.css"></link>
        </Head>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
